[package]
name = "plist-oxide"
description = "Property List editor written in Rust"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.bundle]
name = "PlistOxide"
identifier = "com.ChefKissInc.PlistOxide"
copyright = "Copyright 2022 ChefKiss Inc"
category = "public.app-category.utilities"
icon = ["src/app_icon/icon*.png"]
osx_minimum_system_version = "10.13"
linux_mime_types = ["application/x-plist"]
linux_exec_args = "%f"

[profile.release]
lto = true

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
eframe = { git = "https://github.com/emilk/egui", default-features = false, features = [
    "default_fonts",
    "wgpu",
    "dark-light",
    "persistence",
] }
egui = { git = "https://github.com/emilk/egui", features = [
    "persistence",
    "color-hex",
] }
rfd = "0.10.0"
plist = { version = "1.3.2", git = "https://github.com/ebarnard/rust-plist", features = [
    "enable_unstable_features_that_may_break_with_minor_version_bumps",
] }
serde = "1.0.149"
hex = "0.4.3"
