[package]
name = "plist-oxide"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
eframe = { git = "https://github.com/emilk/egui", default-features = false, features = [
    "default_fonts",
    "wgpu",
    "dark-light",
    "persistence",
    "screen_reader",
] }
egui = { git = "https://github.com/emilk/egui", features = [
    "persistence",
    "color-hex",
] }
rfd = "0.8.2"
plist = "1.3.1"
serde = "1.0.137"
either = "1.6.1"
