[package]
name = "plist-oxide"
description = "Property List editor written in Rust"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.bundle]
name = "PlistOxide"
identifier = "com.ChefKissInc.PlistOxide"
copyright = "Copyright © 2022-2023 ChefKiss Inc. Licensed under the Thou Shalt Not Profit License version 1.0"
category = "public.app-category.utilities"
icon = ["src/app_icon/icon*.png"]
osx_minimum_system_version = "10.13"
linux_mime_types = ["application/x-plist"]
linux_exec_args = "%f"

[profile.release]
lto = true
strip = true

[dependencies]
eframe = { version = "0.22.0", default-features = false, features = [
    "persistence",
    "wgpu",
] }
egui = { version = "0.22.0", features = ["persistence"] }
rfd = "0.11.4"
plist = "1.4.3"
serde = "1.0.163"
hex = "0.4.3"
