[package]
name = "plist-oxide"
description = "Property List editor written in Rust"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.bundle]
name = "PlistOxide"
identifier = "com.ChefKissInc.PlistOxide"
copyright = "Copyright 2022 ChefKiss Inc"
category = "public.app-category.utilities"
icon = ["AppIcon.xcassets/icon*.png"]
osx_minimum_system_version = "10.13"

[profile.release]
lto = true

[dependencies]
eframe = { git = "https://github.com/emilk/egui", default-features = false, features = [
    "default_fonts",
    "wgpu",
    "dark-light",
    "persistence",
    "screen_reader",
] }
egui = { git = "https://github.com/emilk/egui", features = [
    "persistence",
    "color-hex",
] }
rfd = "0.8.2"
plist = { version = "1.3.2", features = [
    "enable_unstable_features_that_may_break_with_minor_version_bumps",
] }
serde = "1.0.137"
either = "1.6.1"
hex = "0.4.3"

[patch.crates-io]
plist = { git = "https://github.com/VisualDevelopment/rust-plist" }
