[package]
description = "Property List editor written in Rust"
edition = "2021"
name = "plist-oxide"
publish = false
version = "0.1.0"

[package.metadata.bundle]
category = "public.app-category.utilities"
copyright = "Copyright © 2022-2024 ChefKiss Inc. Licensed under the Thou Shalt Not Profit License version 1.5"
icon = ["src/app_icon/icon*.png"]
identifier = "com.ChefKissInc.PlistOxide"
linux_exec_args = "%f"
linux_mime_types = ["application/x-plist"]
name = "PlistOxide"
osx_minimum_system_version = "10.13"

[profile.release]
strip = true
lto = "thin"

[dependencies]
winit = { version = "0.29.15", default-features = true }
eframe = { version = "0.26.2", default-features = false, features = [
    "accesskit",
    "persistence",
    "wgpu",
    "wayland",
    "x11",
] }
egui = { version = "0.26.2", default-features = false, features = [
    "persistence",
] }
egui_extras = "0.26.2"
hex = "0.4.3"
plist = "1.6.0"
rfd = "0.14.1"
serde = { version = "1.0.197", features = ["derive"] }
egui-modal = "0.3.5"

[target.'cfg(target_os = "macos")'.dependencies]
icrate = { version = "0.1.0", features = [
    "Foundation",
    "Foundation_NSString",
    "Foundation_NSThread",
    "AppKit",
    "AppKit_NSApplication",
    "AppKit_NSMenu",
    "AppKit_NSMenuItem",
] }

[patch.crates-io]
eframe = { git = "https://github.com/emilk/egui" }
egui = { git = "https://github.com/emilk/egui" }
egui_extras = { git = "https://github.com/emilk/egui" }
