name: Feature Request
description: Request a feature be added to PlistOxide
labels: ["Enhancement"]
projects: ["ChefKissInc/8"]
assignees:
  - VisualEhrmanntraut
body:
  - type: markdown
    attributes:
      value: |
        This form isn't for you to ask for help with your This form isn't for you to ask for help with your computer, PlistOxide or report issues; it's to request features PlistOxide is missing!
  - type: input
    id: os
    attributes:
      label: Operating System
      description: On which OS is the bug occurring?
      placeholder: macOS 11.7.10
    validations:
      required: true
  - type: input
    id: cpu
    attributes:
      label: What is your CPU's model?
      placeholder: ex. AMD Ryzen 5 5600X
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: What is your GPU's model?
      placeholder: ex. AMD Radeon RX 6600 XT
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Please describe the feature in detail.
      placeholder: I want PlistOxide to be able to do Y.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you tried, if any?
      placeholder: I did X to work around the lack of the feature.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Feature request submission terms
      description: By submitting this feature request, you have ensured the following
      options:
        - label: I am using the latest commit of PlistOxide, thereby extension the feature is not already present.
          required: true
        - label: My OS and drivers are up to date.
          required: true
        - label: The feature being present in PlistOxide makes sense.
          required: true
        - label: I have ruled out any external factors that could interfere, including, but not limited to, system modifications the likes of OCLP.
          required: true
    validations:
      required: true
