name: Feature Request
description: Request a feature be added to PlistOxide
labels: ["Enhancement"]
body:
  - type: input
    id: os
    attributes:
      label: Operating System
      description: On which OS is the feature missing, if applicable?
      placeholder: e.g. macOS
  - type: input
    id: cpu
    attributes:
      label: On which CPU is the feature missing, if applicable?
      placeholder: e.g. AMD Ryzen 5 5600X
  - type: input
    id: gpu
    attributes:
      label: On which GPU is the feature missing, if applicable?
      placeholder: e.g. AMD Radeon RX 6600 XT
  - type: textarea
    id: description
    attributes:
      label: Please describe the feature in detail.
      placeholder: I want PlistOxide to be able to do Y.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you tried, if any?
      placeholder: I did X to work around the lack of the feature.
    validations:
      required: true
